---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - ansible-lint --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible 2.7:
  stage: lint
  image:
    name: leandelivery/docker-ansible-ci:ansible-2.7
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

Ansible 2.8:
  stage: lint
  image:
    name: leandelivery/docker-ansible-ci:ansible-2.8
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

AWS Ansible 2.7:
  variables:
    AWS_REGION: us-east-1
  image:
    name: leandelivery/docker-ansible-ci:ansible-2.7
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
    - molecule test -s cloud-aws-direct
  tags:
    - aws

AWS Ansible 2.8:
  variables:
    AWS_REGION: us-east-1
  image:
    name: leandelivery/docker-ansible-ci:ansible-2.8
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
    - molecule test -s cloud-aws-direct
  tags:
    - aws

AWS Windows role from cookiecutter test:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
    - molecule test -s cloud-aws-windows
  tags:
    - aws

EPC role from cookiecutter test:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
