---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - cookiecutter -f --no-input .
    - cd default_role
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - delegated

AWS role from cookiecutter test:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd default_role
    - sed -i 's/ansible-role-//' molecule/cloud-aws-delegated/playbook.yml
    - molecule test -s cloud-aws-delegated
  tags:
    - delegated

EPC role from cookiecutter test:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd default_role
    - sed -i 's/ansible-role-//' molecule/cloud-epc-delegated/playbook.yml
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
