---
dependency:
  name: {{ cookiecutter.dependency_name }}
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: {{ cookiecutter.lint_name }}
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-{{ cookiecutter.role_name }}
    image: ami-9887c6e7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

  - name: test-aws-centos6-{{ cookiecutter.role_name }}
    image: ami-1585c46a
    instance_type: m4.large
    region: us-east-1
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
     - rhel_family

  - name: test-aws-ubuntu16-{{ cookiecutter.role_name }}
    image: ami-09677e0a6b14905b0
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: False
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family

  - name: test-aws-ubuntu18-{{ cookiecutter.role_name }}
    image: ami-012fd5eb46f56731f
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: False
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family

  - name: test-aws-Debian9-{{ cookiecutter.role_name }}
    image: ami-003f19e0e687de1cd
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family

  - name: test-aws-Debian8-{{ cookiecutter.role_name }}
    image: ami-b14ba7a7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family

  - name: test-aws-Windows2016-{{ cookiecutter.role_name }}
    image: ami-0f4c7e570f044b46f
    region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: False
    spot_price: 0.2
    security_group_name:
      - default
    wait_timeout: 1800
    groups:
      - windows

provisioner:
  name: ansible
  log: False
  playbooks:
    create: ../resources/provisioning/WINRM/create.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  lint:
    name: {{ cookiecutter.provisioner_lint_name }}
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-aws-direct
verifier:
  name: {{ cookiecutter.verifier_name }}
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: {{ cookiecutter.verifier_lint_name }}
