---
dependency:
  name: {{ cookiecutter.dependency_name }}
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: {{ cookiecutter.lint_name }}
  options:
    config-file: .yamllint
platforms:

  - name: test-aws-Windows2016-{{ cookiecutter.role_name }}
    aws_image_id: {{ cookiecutter.image_windows2016 }}
    platform: windows2016core
    aws_region: {{ cookiecutter.aws_region }}
    instance_type: {{ cookiecutter.instance_type }}
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows

  - name: test-aws-Windows2019-{{ cookiecutter.role_name }}
    aws_image_id: {{ cookiecutter.image_windows2019 }}
    platform: windows2019core
    aws_region: {{ cookiecutter.aws_region }}
    instance_type: {{ cookiecutter.instance_type }}
    vpc_subnet_id: {{ cookiecutter.vpc_subnet_id }}
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows
{% raw -%}
provisioner:
  name: ansible
  log: false
  connection_options:
    ansible_connection: winrm
  inventory:
    group_vars:
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
{%- endraw %}
  playbooks:
    create: ../resources/provisioning/WINRM/create.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  lint:
    name: {{ cookiecutter.provisioner_lint_name }}
scenario:
  name: cloud-aws-windows
verifier:
  name: {{ cookiecutter.verifier_name }}
  options:
    verbose: true
  lint:
    name: {{ cookiecutter.verifier_lint_name }}
